### PR TITLE
Add option to use PRIVMSG instead of NOTICE

### PR DESCRIPTION
**Pull request by ddevault**
This is desirable in some situations.

I've also included a separate commit which updates this package to use Go modules.

### CODE REVIEW

**Comment by ddevault** [comment]
Note: I'm not going to sign the CLA. My changes are available under the license in my fork, which is unchanged from [your license](https://github.com/google/alertmanager-irc-relay/blob/master/LICENSE). Take it or leave it.

**Comment by shammash** [comment]
Thank you Drew.

Leaving the licensing topic on the side for a second, I'd like to have a better understanding of the reason behind this request.

As far as I can see in the IRC RFC, NOTICE is typically used for automation because, unlike PRIVMSG, "automatic replies MUST NEVER be sent in response to a NOTICE message".

Could you provide a few examples of situations in which PRIVMSG should be used instead of NOTICE ?

Thank you,

Luca

**Comment by ddevault** [comment]
Hey @shammash, on IRC the use of NOTICE or PRIVMSG is not quite as distinct as it once might have been. In practice they're not semantically different, but they do have practical differences which can make them better or worse. For example, for moderation - if you have a bot which use NOTICEs, you must enable NOTICEs for all users, including banned users. PRIVMSG can be moderated more effectively, however. Additionally, some users just prefer the UX of PRIVMSG over NOTICE in their client.

**Comment by ddevault** [comment]
Oh, and if your channel has only one bot in it, or your bot's don't overlap, then it's not going to be a problem in practice, given the reasons you pointed out.

**Comment by shammash** [comment]
Thank you Drew for the additional details.

Now, given that signing the CLA is mandatory for contributing directly with a pull request, is it ok for you to consider this an issue / feature request?

I will reimplement the feature you are asking for.

Thank you,

Luca

**Comment by ddevault** [comment]
Do as you like. Consider me a concientous objector to the CLA.

**Comment by shammash** [comment]
Hi Drew,

https://github.com/google/alertmanager-irc-relay/commit/ae6594c6061e2bcf5a394f70f40eb092247728b8 added use_privmsg .

I am going to close this PR. Please feel free to open an issue if you need other features.

Thank you,

Luca

**Comment by ddevault** [comment]
Thank you.

**Pull request closed without merging**
